# Generated by Django 4.2.1 on 2023-05-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
