# Generated by Django 4.2.1 on 2023-05-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
